ALTER TABLE "DocumentEmbedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DocumentEmbedding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Birthub360CallResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Birthub360CallResult" FORCE ROW LEVEL SECURITY;
