import type { NodeRegistryItem } from './studioTypes.js';

// Global node registry
export const nodeRegistry: Record<string, NodeRegistryItem> = {
  start: {
    type: 'start',
    label: 'Inbound Call Trigger',
    category: 'Start',
    description: 'Triggers when a phone call is received or initiated.',
    iconName: 'Play',
    colorClass: 'bg-green-500 text-green-600',
    inputs: 0,
    outputs: 1,
    version: '1.0.4',
    compatibilities: ['voice', 'llm', 'prompt'],
    dependencies: ['voice-runtime-v1'],
    defaultConfig: {
      channel: 'Telefone',
      language: 'pt-BR',
      timezone: 'America/Sao_Paulo',
      provider: 'Twilio',
      persona: 'Recepção Comercial',
      model: 'Gemini 3.1 Pro',
    },
    documentation: {
      goal: 'Initializes the runtime context, phone connection, and starts the customer call session.',
      inputsDesc: [],
      outputsDesc: ['Call session data containing metadata (ANI, DNIS, caller location).'],
      bestPractices: [
        'Ensure a Voice Configuration is connected immediately downstream to load proper voice output configurations.',
        'Define a default fallback error message in the config.',
      ],
      examples: ['Starts the call with 10k allocated session variables.'],
    },
  },
  voice: {
    type: 'voice',
    label: 'Voice Setup',
    category: 'Voice',
    description: 'Configure active voice parameters, speech rate, and speech synthesis engine.',
    iconName: 'Mic',
    colorClass: 'bg-pink-500 text-pink-600',
    inputs: 1,
    outputs: 1,
    version: '1.1.0',
    compatibilities: ['prompt', 'question', 'start'],
    dependencies: ['elevenlabs-api'],
    defaultConfig: {
      provider: 'ElevenLabs',
      voiceId: 'Rachel_pt_BR',
      stability: 0.75,
      clarity: 0.85,
      speechRate: 1.0,
    },
    documentation: {
      goal: 'Sets up TTS (Text to Speech) parameters to output responses naturally.',
      inputsDesc: ['Call trigger data.'],
      outputsDesc: ['Active voice environment parameters.'],
      bestPractices: [
        'Use ElevenLabs Rachel voice for high-empathy scenarios.',
        'Keep stability below 0.85 for micro-emotional variations.',
      ],
      examples: ['Sets Voice to "Rachel" with ElevenLabs Portuguese-BR translation.'],
    },
  },
  llm: {
    type: 'llm',
    label: 'Gemini 3.1 Pro',
    category: 'AI',
    description: 'Mount Google Gemini Pro LLM configuration with parameters.',
    iconName: 'BrainCircuit',
    colorClass: 'bg-purple-500 text-purple-600',
    inputs: 1,
    outputs: 1,
    version: '1.0.1',
    compatibilities: ['prompt', 'question', 'condition'],
    dependencies: ['gemini-api-v2'],
    defaultConfig: {
      provider: 'Gemini',
      model: 'gemini-2.5-pro',
      temperature: 0.2,
      topP: 0.9,
      maxTokens: 1024,
      safetySettings: 'Strict',
    },
    documentation: {
      goal: 'Binds model logic and generation parameters to the runtime prompt.',
      inputsDesc: ['System properties.'],
      outputsDesc: ['A model session instance bound to execution.'],
      bestPractices: [
        'Keep temperature low (0.1 - 0.3) for structured or factual tasks like appointment booking or lead qualification.',
        'Enable high safety parameters for child-facing bots.',
      ],
      examples: ['Sets Gemini 2.5 Pro with temperature 0.2 and 1024 max tokens.'],
    },
  },
  prompt: {
    type: 'prompt',
    label: 'Atendimento Inicial',
    category: 'Prompt',
    description: 'Executes generative agent instructions, system prompts, or blocks.',
    iconName: 'MessageSquare',
    colorClass: 'bg-iris text-iris',
    inputs: 1,
    outputs: 1,
    version: '1.2.0',
    compatibilities: ['condition', 'switch', 'question', 'human_handoff', 'end'],
    dependencies: ['gemini-api'],
    defaultConfig: {
      promptText:
        'Você é um assistente virtual acolhedor da Birth Voices Hub. Agende compromissos e tire dúvidas dos contatos de forma simpática.',
      streaming: 'Enabled',
      thinking: 'DeepThinking (v2)',
      fallbackText: 'Desculpe, tive um problema técnico. Pode repetir?',
    },
    documentation: {
      goal: 'Injects contextual prompts and compiles model system prompts with reactive variables.',
      inputsDesc: ['Incoming customer intent, voice settings, and model configs.'],
      outputsDesc: ['A generated audio/text string response.'],
      bestPractices: [
        'Structure prompts in Markdown for readability.',
        'Always include a fallback text block to prevent silence.',
      ],
      examples: [
        'Prompt instructing assistants to answer FAQs strictly based on the company knowledge base.',
      ],
    },
  },
  question: {
    type: 'question',
    label: 'Coleta Informação',
    category: 'Conversation',
    description:
      'Speaks a question to the user, records input, validates response, or triggers retries.',
    iconName: 'HelpCircle',
    colorClass: 'bg-teal-500 text-teal-600',
    inputs: 1,
    outputs: 2,
    version: '1.0.5',
    compatibilities: ['condition', 'prompt', 'memory', 'tool'],
    dependencies: ['stt-runtime-v1'],
    defaultConfig: {
      questionText: 'Por favor, me informe o seu nome completo.',
      maxRetryCount: 3,
      speechTimeoutMs: 5000,
      validationRegex: '^[A-Za-z ]{5,50}$',
      variableToSave: 'customer_name',
      fallbackPrompt: 'Não entendi. Poderia dizer seu nome novamente?',
    },
    documentation: {
      goal: 'Asks for, listens to, captures, and validates structured slot values from caller speech.',
      inputsDesc: ['Call session context.'],
      outputsDesc: ['Slot value verified successfully (Out 0) or fallback limit exceeded (Out 1).'],
      bestPractices: [
        'Configure explicit validation regexes to filter out noise.',
        'Always keep the speech timeout under 6000ms.',
      ],
      examples: ['Capture telephone numbers or document values through speech synthesis inputs.'],
    },
  },
  condition: {
    type: 'condition',
    label: 'Filtro Intenção',
    category: 'Decision',
    description: 'Branch the flow on conditional checks of variables or natural language intents.',
    iconName: 'GitBranch',
    colorClass: 'bg-orange-500 text-orange-600',
    inputs: 1,
    outputs: 2,
    version: '1.0.0',
    compatibilities: ['prompt', 'tool', 'human_handoff', 'knowledge'],
    dependencies: [],
    defaultConfig: {
      variable: 'intent',
      operator: 'equals',
      value: 'Suporte',
      naturalLanguageCheck: 'false',
      matchConfidenceThreshold: 0.8,
    },
    documentation: {
      goal: 'Branches execution routes based on exact variable matching or intent scores.',
      inputsDesc: ['Execution variables.'],
      outputsDesc: ['Output branch matching check (Out 0) or fallback branch (Out 1).'],
      bestPractices: [
        'Always connect a default fallback branch to prevent frozen flow status.',
        'Use Intent variables populated by LLM prompt nodes.',
      ],
      examples: ['Branches the flow to Human Handoff if "intent == Suporte".'],
    },
  },
  switch: {
    type: 'switch',
    label: 'Switch Menu',
    category: 'Logic',
    description:
      'Evaluate multi-path switch routing checks matching multiple values or categories.',
    iconName: 'Split',
    colorClass: 'bg-yellow-500 text-yellow-600',
    inputs: 1,
    outputs: 3,
    version: '1.0.0',
    compatibilities: ['prompt', 'tool', 'human_handoff', 'knowledge', 'end'],
    dependencies: [],
    defaultConfig: {
      variableToCheck: 'userIntent',
      path0: 'Agendamento',
      path1: 'Suporte',
      path2: 'Financeiro',
    },
    documentation: {
      goal: 'Route workflows across multiple channels depending on slot category tags.',
      inputsDesc: ['Context payload.'],
      outputsDesc: ['Branch 0, Branch 1, Branch 2 matching conditions.'],
      bestPractices: ['Map each path option directly to customer service department queues.'],
      examples: [
        'Routes caller directly to different queues based on selected telephone menu options.',
      ],
    },
  },
  knowledge: {
    type: 'knowledge',
    label: 'Notion FAQs',
    category: 'Knowledge',
    description:
      'Search document repositories, web links, or structured FAQ knowledge bases using vector RAG.',
    iconName: 'BookOpen',
    colorClass: 'bg-cyan-500 text-cyan-600',
    inputs: 1,
    outputs: 1,
    version: '1.0.2',
    compatibilities: ['prompt', 'condition', 'end'],
    dependencies: ['vector-db-notion'],
    defaultConfig: {
      database: 'Notion FAQs',
      ragTopK: 3,
      minScoreThreshold: 0.72,
      searchStrategy: 'Embeddings + Semantic Match',
      autoChunkSize: 512,
    },
    documentation: {
      goal: 'Queries indexed FAQs and embeds context directly into current generation systems.',
      inputsDesc: ['User question or prompt keywords.'],
      outputsDesc: ['Text chunks with references containing validated facts.'],
      bestPractices: [
        'Format source files with clear heading titles.',
        'Upload small factual PDF articles instead of generic books.',
      ],
      examples: ['Queries commercial FAQ files on Notion to answer lead questions.'],
    },
  },
  tool: {
    type: 'tool',
    label: 'REST API Integration',
    category: 'Integration',
    description: 'Perform HTTP REST webhooks, CRM queries, or SQL commands synchronously.',
    iconName: 'Wrench',
    colorClass: 'bg-brand text-brand-ink dark:text-brand',
    inputs: 1,
    outputs: 1,
    version: '2.0.0',
    compatibilities: ['condition', 'prompt', 'end'],
    dependencies: ['node-fetch-middleware'],
    defaultConfig: {
      method: 'POST',
      endpoint: 'https://api.birthhub360.com.br/v1/leads',
      headers: '{"Authorization": "Bearer token_secret"}',
      bodyPayload: '{"name": "{{customer_name}}", "date": "{{meeting_date}}"}',
      timeoutMs: 4000,
      retryLimit: 2,
    },
    documentation: {
      goal: 'Fires REST webhooks or fetches enterprise CRM databases in active sessions.',
      inputsDesc: ['Active flow parameters.'],
      outputsDesc: ['API response parsed into global state.'],
      bestPractices: [
        'Do not send sensitive API keys in public headers.',
        'Always check payload schemas prior to publishing.',
      ],
      examples: ['Book a commercial meeting slot by communicating with external backends.'],
    },
  },
  memory: {
    type: 'memory',
    label: 'State Manager',
    category: 'Memory',
    description: 'Write, pull, reset, or update execution session variables in memory database.',
    iconName: 'Database',
    colorClass: 'bg-emerald-500 text-emerald-600',
    inputs: 1,
    outputs: 1,
    version: '1.0.0',
    compatibilities: ['prompt', 'tool', 'end'],
    dependencies: [],
    defaultConfig: {
      operation: 'Set Variable',
      variableName: 'hasCompletedSurvey',
      variableValue: 'true',
      scope: 'Session',
    },
    documentation: {
      goal: 'Saves or updates custom session identifiers inside the client persistence storage.',
      inputsDesc: ['Context state.'],
      outputsDesc: ['State updated successfully.'],
      bestPractices: [
        'Prefix variable names with domain descriptors (e.g., user_last_appointment_id).',
      ],
      examples: ['Set customer survey feedback variables in runtime database memory.'],
    },
  },
  human_handoff: {
    type: 'human_handoff',
    label: 'Suporte Técnico',
    category: 'Human',
    description:
      'Transfers call immediately to a live customer service operator, updating call queues.',
    iconName: 'Headphones',
    colorClass: 'bg-rose-500 text-rose-600',
    inputs: 1,
    outputs: 0,
    version: '1.0.0',
    compatibilities: [],
    dependencies: ['sip-trunk-router'],
    defaultConfig: {
      department: 'Suporte Técnico',
      fallbackNumber: '+5511999999999',
      ringTimeoutSec: 30,
      recordCall: 'true',
      transferMessage: 'Aguarde um momento enquanto encaminho sua ligação.',
    },
    documentation: {
      goal: 'Bridge live telecommunications voice streams over directly to human customer support teams.',
      inputsDesc: ['Session identifier.'],
      outputsDesc: [],
      bestPractices: [
        'Ensure department configurations match valid PBX lines.',
        'Always record calls for analytics quality control checks.',
      ],
      examples: ['Routing active customer support queries directly to tech support agents.'],
    },
  },
  end: {
    type: 'end',
    label: 'Finalizar Conversa',
    category: 'Control',
    description:
      'Closes call socket gracefully, saves transcripts, runs final dashboard summaries.',
    iconName: 'Square',
    colorClass: 'bg-slate-700 text-slate-800',
    inputs: 1,
    outputs: 0,
    version: '1.0.0',
    compatibilities: [],
    dependencies: ['voice-runtime-v1'],
    defaultConfig: { saveTranscript: 'true', exportToWebhook: 'false', postCallSurvey: 'Disabled' },
    documentation: {
      goal: 'Teardown the active customer connection socket gracefully and compute conversational KPIs.',
      inputsDesc: ['Flow state.'],
      outputsDesc: [],
      bestPractices: [
        'Always export logs to webhooks if building analytics reports.',
        'Enable transcripts for compliance audits.',
      ],
      examples: ['Saves conversation summary and closes customer connection successfully.'],
    },
  },
};
